### ISSUE TITLE
git remote command error code 128 ... help me

### ISSUE THREAD

**Issue by lbs8901** [jacogr/atom-git-control#120]
> git status --porcelain --untracked-files=all
> git fetch --prune
> fatal: could not read Username for 'https://gitlab.com': Device not configured
> 'git fetch --prune' exited with error code 128
## .git/config setting

[user]
name = foo
email = foo@bar.com

How do I fix the problem.. help me..

**Comment by MarcelMue** [comment]
Sounds like a problem related to gitlab and not git-control. I am not a gitlab user so I am unaware about the problem. A SSH setupt could be better though (if you aren't using it?)

**Comment by n-a-m-e** [comment]
I got that error as well because, git control doesn't give you the opportunity to enter your username and password each time you push, you have to be using ssh or have your username and password for git cached so that it doesn't prompt you each time. If your using ubuntu or arch-linux just follow the advice here
http://stackoverflow.com/questions/13385690/how-to-use-git-with-gnome-keyring-integration/13390889
and then git push once from the terminal, after that your credentials are saved in your keyring and you should be able to use git control inside atom :-)

**Comment by ngmgithub** [comment]
Same issue on Mac OS X 10.11.4 El Capitan. Could git-control offer a way to enter and securely store git credentials rather than leaving it in plain text in .git/config?
