### ISSUE TITLE
[Feature Request] Pull Request

### ISSUE THREAD

**Issue by rickydazla** [jacogr/atom-git-control#44]
Loving this package! It would be great to have a button/shortcut to create pull requests.

**Comment by SerenadeX** [comment]
👍🏻

**Comment by MarcelMue** [comment]
This is not on the roadmap for this project right now.

**Comment by nounoursheureux** [comment]
As discussed on Gitter, this is mainly because Pull Requests are Github-specific, so to add this feature the package would need to ask the user for his Github credentials. This package isn't Github-specific so asking for the Github credentials would be weird. Maybe this feature will be implemented when Atom will have a built-in support for Github authentication.
